version: '3'

services:
  

  redis:
    image: 'redis:alpine'
    hostname: redis
    networks:
      - live

  
  web:
    build: .
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    container_name: service
    volumes:
      - .:/service
    ports:
      - "8000:8000"

  nginx:
    image: nginx
    hostname: nginx
    ports:
      - '82:8000'
    volumes:
      - ./nginx:/etc/nginx/conf.d
    
    networks:
      - live

  celery:
    build:
      context: .
    command: "celery -A fampay worker --beat -l info"
    
    restart: on-failure
    networks:
      - live



networks:
  live:


