# Generated by Django 4.1.2 on 2022-12-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='youtube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('publishing_datetime', models.DateTimeField()),
                ('thumbnails_URLs', models.URLField()),
            ],
        ),
    ]
